### ISSUE TITLE
Help with license

### ISSUE THREAD

**Issue by vchhasatia** [alexharri/map-fns#32]
Hello team,

I was wondering if it is possible to clarify your license in npm (https://www.npmjs.com/package/map-fns). I realized that your package is under MIT license on GitHub, but it lacks license on npm page.

Thank you very much for reviewing this issue.

**Comment by alexharri** [comment]
Hey, thanks for reaching out!

The license is not being included in the npm bundle because of an oversight in the `build:copy-files` script in `package.json`, which failed to copy `LICENSE`.

I've amended that in #33, but it seems that the release CI run failed ([see run](https://github.com/alexharri/map-fns/actions/runs/6789479793/job/18456756446)). Might be an expired CI token or outdated dependencies (I don't have time to analyze now).

I'll take a look at fixing the release this weekend, I have some free time then.

**Comment by alexharri** [comment]
Sorry for the wait! The npm page now correctly shows this package as MIT licensed (and the LICENSE file is included in the package contents)
